In [7]:
import numpy as np

In [10]:
#Convert python list to numpy array
a=[1,2,3,4]

b=[[1,2,3,4],[4,5,6,7]]



np_arrayA=np.array(a)

np_arrayB=np.array(b)

print(np_arrayA)
print(np_arrayB)



[1 2 3 4]
[[1 2 3 4]
 [4 5 6 7]]


In [9]:
#get the dimension of the numpy array
print(np_arrayA.shape) 
print(np_arrayB.shape)

(4,)
(2, 4)


In [38]:

#numpy array operations

np_arrayD=np_arrayA+np_arrayB
print(np_arrayD)

np_arrayE=np_arrayA*np_arrayB
print(np_arrayE)


[[ 2  4  6  8]
 [ 5  7  9 11]]
[[ 1  4  9 16]
 [ 4 10 18 28]]


In [11]:
#accessing elements of numpy array

a=[1,2,3,4]
b=[[1,2,3,4],[4,5,6,7]]

np_arrayA=np.array(a)
np_arrayB=np.array(b)

#Access one dimension array
print(np_arrayA[0])

#Access two dimension array
print(np_arrayB[1,2])


1
6


In [42]:
#numpy array indexing

np_arrayP=np.array([1,2,3,4,5])
print(np_arrayP[np.array([0,2,4])]) #indexing using a numpy array


[1 3 5]


In [12]:

#numpy array slicing
'''[[1 2 3 4]
 [4 5 6 7]]'''

print(np_arrayB[:,1]) #print the second column

print(np_arrayB[1,:1:2]) #print the second row

[2 5]
[4]


In [6]:
#numpy array mathematical functions

print(np.sum(np_arrayA)) #sum of all elements
print(np.min(np_arrayA)) #minimum element
print(np.max(np_arrayA)) #maximum element
print(np.mean(np_arrayA)) #mean of elements

print(np.std(np_arrayA)) #standard deviation of elements


10
1
4
2.5
1.118033988749895


In [ ]:
#numpy array sorting

np_arrayG=np.array([5,3,8,1,2])
print(np.sort(np_arrayG)) #sorting in ascending order

In [13]:

#numpy array filtering

np_arrayH=np.array([5,3,8,1,2])
print(np.where(np_arrayH>3)) #indices of elements greater than 3

(array([0, 2]),)


In [ ]:

#numpy array unique values

np_arrayI=np.array([5,3,8,1,2,3,5])
print(np.unique(np_arrayI)) #unique values in the array


In [ ]:
#numpy array concatenation

np_arrayJ=np.array([1,2,3])
np_arrayK=np.array([4,5,6])
print(np.concatenate((np_arrayJ,np_arrayK))) #concatenate two arrays

In [44]:
#numpy array splitting

np_arrayL=np.array([1,2,3,4,5,6,7,8,9])

print(np.split(np_arrayL,3)) #split the array into three parts

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
'''Numpy Stack Functions'''

In [14]:
'''This code demonstrates the use of np.stack() to combine multiple 1D arrays into a single 2D array. Let's break it down:

Three 1D NumPy arrays are created: np_arrayM, np_arrayN, and np_array.
The np.stack() function is used to combine these arrays vertically.
By default, np.stack() stacks arrays along a new axis (axis=0), which in this case results in a 2D array where each input array becomes a row.'''

#numpy array stacking

np_arrayM=np.array([1,2,3])
np_arrayN=np.array([4,5,6])
np_arrayO=np.array([7,8,9])
print(np.stack((np_arrayM,np_arrayN,np_arrayO))) #stack arrays vertically


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
'''Numpy Vertical Stack Functions.
Stacks arrays vertically (row-wise), similar to the default behavior of np.stack().
'''
#Stacks arrays Vertical (column-wise).

np_arrayV=np.array([[1,2,3],[4,5,6]])
np_arrayW=np.array([[7,8,9],[10,11,12]])
print(np.vstack((np_arrayV,np_arrayW))) #stack arrays Vertically

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
'''Horizontal Stack Functions.
np.hstack(): Stacks arrays horizontally (column-wise).
'''  
#Stack arrays Horizontally

np_arrayT=np.array([[1,2,3],[4,5,6]])
np_arrayU=np.array([[7,8,9],[10,11,12]])
print(np.hstack((np_arrayT,np_arrayU))) #stack arrays horizontally

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [50]:
'''Depth wise stack
np.dstack(): Stacks arrays along the third axis (depth-wise).
'''
np_arrayV=np.array([[1,2,3],[4,5,6]])
np_arrayW=np.array([[7,8,9],[10,11,12]])
print(np.dstack((np_arrayV,np_arrayW))) #stack arrays depth-wise

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [61]:
'''
Concatenate
np.concatenate(): Joins arrays along an existing axis. It's more flexible but requires you to specify the axis.
'''

np_arrayX=np.array([[1,2,3],[4,5,6]])
np_arrayY=np.array([[7,8,9],[10,11,12]])
np_arrayZ=np.array([[7,8,9],[10,11,12]])
print(np.concatenate((np_arrayX,np_arrayY,np_arrayZ),axis=0)) #stack arrays horizontally along the specified axis

#For Axis you can use either 0 or 1 for this scenario. Because the array is 2 dimensional.
#If you give axis=2 you will get error. The Reason is below.
'''We create three 2D arrays: np_arrayX, np_arrayY, and np_arrayZ. Each of these arrays has a shape of (2, 3), meaning 2 rows and 3 columns.
The code attempts to concatenate these arrays along axis=2. However, this will raise an error because these 2D arrays don't have a third axis (axis 2).
In NumPy, axes are numbered starting from 0:

axis=0 represents rows
axis=1 represents columns
axis=2 would represent depth in a 3D array, but our arrays are only 2D'''

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 7  8  9]
 [10 11 12]]


"We create three 2D arrays: np_arrayX, np_arrayY, and np_arrayZ. Each of these arrays has a shape of (2, 3), meaning 2 rows and 3 columns.\nThe code attempts to concatenate these arrays along axis=2. However, this will raise an error because these 2D arrays don't have a third axis (axis 2).\nIn NumPy, axes are numbered starting from 0:\n\naxis=0 represents rows\naxis=1 represents columns\naxis=2 would represent depth in a 3D array, but our arrays are only 2D"

In [74]:
'''What is three dimensional array?
3D array is a three-dimensional structure. It can be viewed as a stack of 2D arrays. Each element in a 3D array can be accessed using three indices, one for the stack, another for the row, and another for the column.'''

array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
print(np.concatenate((array1,array2),axis=2)) #stack arrays horizontally along the specified axis

[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.


Why is NumPy Faster Than Lists?
NumPy use fixed types and   functions.
No type checking when iterating through objects.
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.



What is one dimensional array?
A one-dimensional array can be viewed as a linear sequence of elements.

What is two dimensional array?
Collection of one D array is called 2D array.
2D array is a two-dimensional structure. It can be viewed as a grid of elements. Each element in a 2D array can be accessed using two indices, one for the row and another for the column.

What is three dimensional array?
3D array is a three-dimensional structure. It can be viewed as a stack of 2D arrays. Each element in a 3D array can be accessed using three indices, one for the stack, another for the row, and another for the column.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


