In [1]:
from numpy import random

x=random.choice([3,10,5,4,6],p=[0.1,0.2,0.3,0.3,0.1],size=(10))
print(x)

[ 4 10  3  5  5  4 10  4  5  4]


Random Permutations of Elements
A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: shuffle() and permutation().


Permutation()

The permutation() method returns a re-arranged array (and leaves the original array un-changed).

In [26]:
from numpy import random
import numpy as np

arr1=np.array([5,6,7,8,9])
arra2=random.permutation(arr1)


print(arr1)# Original array as it is

print(arra2) #Shuffled array

[5 6 7 8 9]
[5 7 8 9 6]


Shuffling Arrays
Shuffle means changing arrangement of elements in-place. i.e. in the array itself. In the assign it will give only blank.
It will make the changes in the original array itself.

In [29]:
from numpy import random
import numpy as np

arr1=np.array([5,6,7,8,9])
arra2=random.shuffle(arr1)

print(arr1)

print(arra2) #It will not give the Shuffled value. you will get null only.

[7 8 9 6 5]
None
